apiVersion: monitoring.coreos.com/v1
kind: PodMonitor

metadata:
  name: application
  namespace: monitoring

spec:
  selector:
    matchLabels:
      app: application

  podMetricsEndpoints:
    - port: "5000"
      targetPort: 5000
      interval: 30s
      path: /metrics
